name: CI MLflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL: "Project/wine-quality.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM_STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check env
        run: |
          echo $CSV_URL


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run mlflow project
        run: |
          mlflow run Project --env-manager=local
